### ISSUE TITLE
ImageIndex

### ISSUE THREAD

**Issue by limelect** [DGH2112/DGH-IDE-Notifiers#1]
On d10.2.1 i had to change on DGHDockableIDENotificationsForm.pas
at 
Procedure TfrmDockableIDENotifications.LogViewGetImageIndex(Sender: TBaseVirtualTree;
  Node: PVirtualNode; Kind: TVTImageKind; Column: TColumnIndex; Var Ghosted: Boolean;
  Var ImageIndex:TImageIndex);  << it was integer

// Integer);

P.S where is the log. cannot find it. It name?

**Comment by DGH2112** [comment]
For backward compatibility to RAD Studio 2009 this code was built with VirtualTrees 5.3. This method was changed in circa VirtualTrees 6.2 where they have changed that calling parameter however the 6.x version have limited backward compatibility.

The code will remain compatible with 5.x of VirtualTrees so that it can be compiled back for 2009 (VirtualTrees 5.3 is one of the repositories on my GitHub area for this reason).

The log file is the DLL name with .log at the end in the user's profile (`%AppData%\Roaming\Season's Fall\`). Have a look at the method:

`Function TfrmDockableIDENotifications.ConstructorLogFileName : String;`

regards
Dave.
